### ISSUE TITLE
Unclear License

### ISSUE THREAD

**Issue by soerup** [jcchurch13/Encoder#1]
Hi, 

The license of your work in unclear, can I post some code on Github as a derivative of yours with an Open Source license or similar? 

/Lars

**Comment by jcchurch13** [comment]
Hi Lars, sorry about that.   Yes, you can!  This work is released under the [Creative Commons Attribution Share-Alike 4.0 License.](https://creativecommons.org/licenses/by-sa/4.0/) 

I've added that to the readme.
